apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app
  labels:
    app: fitness-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
      - name: fitness-app
        image: h4meed/fitness-backend:latest
        ports:
        - containerPort: 3000