apiVersion: v1
kind: Service
metadata:
  name: fitness-frontend-service
spec:
  type: NodePort
  selector:
    app: fitness-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081

